### ISSUE TITLE
How can I concatenate multiple `muon` data samples?

### ISSUE THREAD

**Issue by danli349** [scverse/muon#127] opened 2023-09-13 17:47 UTC
Hello:

How can I concatenate multiple `muon` data samples? Thanks
I tried:
```
mdata.concatenate(mdata2, batch_key='sample_id')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 1
----> 1 mdata.concatenate(mdata2, batch_key='sample_id')

AttributeError: 'MuData' object has no attribute 'concatenate'
```

```
import anndata as ad
ad.AnnData.concatenate(mdata, mdata2, batch_key='sample_id')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 2
      1 import anndata as ad
----> 2 ad.AnnData.concatenate(mdata, mdata2, batch_key='sample_id')

File ~/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py:1770, in AnnData.concatenate(self, join, batch_key, batch_categories, uns_merge, index_unique, fill_value, *adatas)
   1767     adatas = adatas[0]  # backwards compatibility
   1768 all_adatas = (self,) + tuple(adatas)
-> 1770 out = concat(
   1771     all_adatas,
   1772     axis=0,
   1773     join=join,
   1774     label=batch_key,
   1775     keys=batch_categories,
   1776     uns_merge=uns_merge,
   1777     fill_value=fill_value,
   1778     index_unique=index_unique,
   1779     pairwise=False,
   1780 )
   1782 # Backwards compat (some of this could be more efficient)
   1783 # obs used to always be an outer join
   1784 out.obs = concat(
   1785     [AnnData(sparse.csr_matrix(a.shape), obs=a.obs) for a in all_adatas],
   1786     axis=0,
   (...)
   1790     index_unique=index_unique,
   1791 ).obs

File ~/miniconda3/lib/python3.8/site-packages/anndata/_core/merge.py:873, in concat(adatas, axis, join, merge, uns_merge, label, keys, index_unique, fill_value, pairwise)
    870 X = concat_Xs(adatas, reindexers, axis=axis, fill_value=fill_value)
    872 if join == "inner":
--> 873     layers = inner_concat_aligned_mapping(
    874         [a.layers for a in adatas], axis=axis, reindexers=reindexers
    875     )
    876     concat_mapping = inner_concat_aligned_mapping(
    877         [getattr(a, f"{dim}m") for a in adatas], index=concat_indices
    878     )
    879     if pairwise:

File ~/miniconda3/lib/python3.8/site-packages/anndata/_core/merge.py:459, in inner_concat_aligned_mapping(mappings, reindexers, index, axis)
    456 def inner_concat_aligned_mapping(mappings, reindexers=None, index=None, axis=0):
    457     result = {}
--> 459     for k in intersect_keys(mappings):
    460         els = [m[k] for m in mappings]
    461         if reindexers is None:

File ~/miniconda3/lib/python3.8/site-packages/anndata/_core/merge.py:68, in intersect_keys(ds)
     67 def intersect_keys(ds: Collection) -> OrderedSet:
---> 68     return reduce(and_, map(OrderedSet, ds))

File ~/miniconda3/lib/python3.8/site-packages/anndata/_core/merge.py:32, in OrderedSet.__init__(self, vals)
     31 def __init__(self, vals=()):
---> 32     self.dict = OrderedDict(zip(vals, repeat(None)))

TypeError: 'NoneType' object is not iterable
```

**Comment by gtca** [comment] 2023-09-13 23:23
Hey @danli349!

As the `AttributeError` says, this is just something that hasn't been implemented yet. Concatenation API is scheduled for the next version of mudata (also see https://github.com/scverse/mudata/issues/20)!

Please note that `anndata.AnnData.concatenate()` has been deprecated [in favour of `anndata.concat()`](https://anndata.readthedocs.io/en/latest/concatenation.html) since `anndata v0.9`.

**Comment by gtca** [comment] 2023-09-13 23:28
Closing it as duplicate of https://github.com/scverse/muon/issues/64.

**Closed by gtca** 2023-09-13 23:28 UTC
